name: Send PMtiles to project repo
on: [workflow_dispatch]

jobs:
  Get-Daily-Builds:
    runs-on: ubuntu-latest
    steps:
    # - run: echo "Hello World!"
    # - run: wget https://github.com/protomaps/go-pmtiles/releases/download/v1.20.0/go-pmtiles_1.20.0_Linux_x86_64.tar.gz
    # - run: tar -zxvf go-pmtiles_1.20.0_Linux_x86_64.tar.gz
    # - run: ./pmtiles -h
      - run: wget -q --spider "https://build.protomaps.com/$(date +%Y%m%d).pmtiles" && wget "https://build.protomaps.com/$(date +%Y%m%d).pmtiles" || wget "https://build.protomaps.com/$(date -d 'yesterday' +%Y%m%d).pmtiles"
      - run: echo "Downloaded: $(ls | grep 'pmtiles')"
      
